-------- ödev4---------
--1.select distinct replacement_cost from film;
--2.select count(distinct replacement_cost) from film;
--3.select count(*) from film where title LIKE 'T%' and rating='G';
--4.select distinct country from country where length(country)=5;
--5.select count(city) from city where city ILIKE '%r' ;